# Generated by Django 2.1.7 on 2021-02-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        ('buyer', '0002_auto_20210211_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='placed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learn.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='amt_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='processing', max_length=40),
        ),
    ]
